popup window
mumbereh/my-portfolio pull request #13
Opened 2023-06-19 14:33 UTC by mumbereh

### **Description**
In this milestone of my  portfolio website, I have  implement a popup window that includes the project details in both desktop and mobile.

### **I implemented the following in this branch**

> 1. I JavaScript array to store all of the information for all projects.
> 2. I stored the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
> 3. I  updated the main page so that the projects section is created dynamically using the information stored in that JavaScript object. And all of the HTML in that section is created when the page loads.
> 4. Finally I implemented  popup window.
> 5. When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
> 6. When the user clicks (or taps) the close (X) button, the popup disappears.
> 7. In order to associate each project with the popup window details,
> 8.

2023-06-19 22:43 UTC, LionRouge1 requested changes
Hi **Team**, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good job implementing the mobile menu, it looks almost identical to the figma design :+1: 
- Nice work following JavaScript best practices :1st_place_medal:  
- All linters passed :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

[OPTIONAL]
- [ ] Nice work implementing the mobile menu, everything looks fine :+1: :sunglasses: However it would be nice to add `position: fixed` to the `nav` in your `style.css` file at line 132 to prevent it scroll with the page.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-19 22:43 UTC, LionRouge1 commented on index.html
>          </div>
- [ ] Please do not push commented out code to your code base, It make your project look messy. Therefore I suggest you remove all commented out code from your project.

2023-06-19 22:43 UTC, LionRouge1 commented on index.html
>          </div>
- [ ] Same here as pointed out earlier :point_up_2:

2023-06-19 22:43 UTC, LionRouge1 commented on index.html
> +
- [ ] Same here as pointed out earlier :point_up_2:

2023-06-19 22:43 UTC, LionRouge1 commented on index.html
> +           <--</section> -->
- [ ] Same here as pointed out earlier :point_up_2:

2023-06-20 05:09 UTC, 1GORDON reviewed
##
## Hi @mumbereh, and @Wineshuga ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ] You have submitted a project with failing linter checks. Kindly make sure your linter checks are passing and are in green.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 05:45 UTC, mumbereh commented
Hello there I thank you for receiving my request for review for PR:
https://github.com/mumbereh/my-portfolio/pull/13.

The first reviewer requested changes. I worked on them and submitted them
for the second review.

*The second reviewer *
On Tue, 20 Jun 2023 at 08:09, Gordon Tinyefuza ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> Hi @mumbereh <https://github.com/mumbereh>, and @Wineshuga
> <https://github.com/Wineshuga> ✋
>
> Good job so far!
>
> Hello ✋, you have done well reaching this point of the milestone 🤝 . But
> there are some issues that you still need to work on to go to the next
> project but you are almost there!
> This project will be marked as Invalid and won't affect the number of your
> weekly reviews.
>
>    -  You have submitted a project with failing linter checks. Kindly
>    make sure your linter checks are passing and are in green.
>
> Cheers, and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread and tag me
> @1GORDON if something is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>

I did my best basing on the information below
https://microverse-students.slack.com/archives/C47D4N35M/p1686654751539179
Marco Lizza
Hey Micronauts ***@***.****! [image: :wave:]I hope you're doing well! We are
aware that most of you are experiencing Webhint issues, we are currently
working on a solution[image: :male-technologist:].For now, please go ahead
and request for review if you only have the Webhint error on your PR. Our
CRs would be happy to review your PRs [image: :slightly_smiling_face:].
Show more

[image: review.PNG]
kindly advise me. since the linter error seems not to be mine but
technical.

> Thank you i really appreciate all. Message ID:
> ***@***.***>
>

2023-06-20 06:59 UTC, Shisui6 approved these changes
Hi @mumbereh, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉.  

## Highlights 🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 07:10 UTC, wayungi reviewed
Hi @mumbereh , 
![image](https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a PR that was is already approved about 10 minutes ago. Please submit a new PR for every milestone

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-20 09:25 UTC, V-Blaze approved these changes
Hi @mumbereh  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Correct GitHub Flow💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 09:28 UTC, merged

2023-06-20 09:42 UTC, mumbereh commented
Thank you


On Tue, 20 Jun 2023 at 12:25, VALENTINE BLAZE ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @mumbereh <https://github.com/mumbereh> ,
> Approved 🟢 🟢
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> [image: giphy]
> <https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif>
> Highlights
>
>    - Correct GitHub Flow💯
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mumbereh/my-portfolio/pull/13#pullrequestreview-1487712521>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZTLCE7L6RMZPGS4HGNX5SLXMFUBHANCNFSM6AAAAAAZMBFABY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>