Desk top version
mumbereh/my-portfolio pull request #5
Opened 2023-06-05 21:51 UTC by mumbereh

I this branch I have added media query to the make the portfolio responsive

2023-06-05 23:22 UTC, Shedrack-Sunday requested changes
Hello @mumbereh       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there's one adjustment you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Nice efforts on the UI designs✔️  
  
# Required Changes  🌵 

- [x] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirements 


_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-05 23:22 UTC, Shedrack-Sunday commented on index.html
> +                    </ul>
- [ ] Kindly adjust  the socail icons on the desktop view to be aligned with the paragrah and text around it.
- Look at the image comparison bellow to have a very detailed view. This gives a better user experince and will enhance your attention to details in replating designs given 👍 

## Your design:
![image](https://github.com/mumbereh/my-portfolio/assets/50990925/1d6e534d-5d14-41ac-88a3-102898a03ac8)

## Figma:
![image](https://github.com/mumbereh/my-portfolio/assets/50990925/46eed7ee-54ab-495c-b701-113abf773bab)

2023-06-05 23:22 UTC, Shedrack-Sunday commented on index.html
> +                    <li class="other-skills">javascript</li>
- [ ] The skills listed in each of the cards on the figma design are aligned horizontally and well spaced. You can see how they give a very nice visual view and will  definitely draw the attention of a viewer. E.g a hiring manager.
- Kindly adjust yours in that regard. `flexbox` will make implementing that functionality very seamless. 

## Your work:
![image](https://github.com/mumbereh/my-portfolio/assets/50990925/aa903ae0-f870-4058-9bab-e3be22e8492f)

## Figma deisgn:
![image](https://github.com/mumbereh/my-portfolio/assets/50990925/c3e85599-6d50-4ddd-9e99-754f245be891)

2023-06-05 23:22 UTC, Shedrack-Sunday commented on index.html
> +            <div class="social-media">
- [ ] Firstly, kindly adjust the space between the `header` content text and social icons to be a replica of the design given 👍 
- [ ] Secondly, lets adjust the placemnt of the background image. You can see the botton dots is lacking on your design. These chanages might seem minor to you, but as a developer, you're tasked to replicated the works of poduct designsers, of which they take every detail into consideration. In prepario for clients and your mangers work, kindly align the image text properly 👍 
## Your view:
![image](https://github.com/mumbereh/my-portfolio/assets/50990925/1474f393-fd67-4814-aec4-dce7019a4e3a)

## Figma view:
![image](https://github.com/mumbereh/my-portfolio/assets/50990925/5be65128-302e-4be0-bb01-5e92fd0042a0)

2023-06-06 06:54 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @mumbereh , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Great design
✅ ... Clean code

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 12:21 UTC, merged